"""Added required tables

Revision ID: b3772c5f957c
Revises: 
Create Date: 2022-08-19 14:48:02.508758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3772c5f957c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    op.drop_table('series')
    op.drop_table('author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id_author', sa.INTEGER(), nullable=False),
    sa.Column('name_author', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id_author')
    )
    op.create_table('series',
    sa.Column('id_series', sa.INTEGER(), nullable=False),
    sa.Column('name_series', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id_series')
    )
    op.create_table('model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), nullable=True),
    sa.Column('load_capacity', sa.INTEGER(), nullable=True),
    sa.Column('engine_power', sa.INTEGER(), nullable=True),
    sa.Column('transmission', sa.VARCHAR(length=32), nullable=True),
    sa.Column('torque', sa.INTEGER(), nullable=True),
    sa.Column('fuel_consumption', sa.INTEGER(), nullable=True),
    sa.Column('tires', sa.VARCHAR(length=32), nullable=True),
    sa.Column('max_speed', sa.INTEGER(), nullable=True),
    sa.Column('turning_radius', sa.FLOAT(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('id_series', sa.INTEGER(), nullable=True),
    sa.Column('id_author', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['author.id_author'], ),
    sa.ForeignKeyConstraint(['id_series'], ['series.id_series'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
